name: sendero_ambiental_unillanos
description: App guia del sendero ambiental de la universidad de los llanos
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0


dev_dependencies:

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/imagen_principal.jpg
      - assets/images/estacion1.png
      - assets/images/estacion2.png
      - assets/images/estacion3.png
      - assets/images/estacion4.png
      - assets/images/estacion6.png
      - assets/images/estacion7.png
      - assets/images/estacion8.png
      - assets/images/estacion10.png
      - assets/images/estacion11.png
      - assets/images/estacion14.png
      - assets/offlineMap/16/19370/32024.png
      - assets/offlineMap/16/19370/32025.png
      - assets/offlineMap/16/19370/32026.png
      - assets/offlineMap/16/19370/32027.png
      - assets/offlineMap/16/19371/32024.png
      - assets/offlineMap/16/19371/32025.png
      - assets/offlineMap/16/19371/32026.png
      - assets/offlineMap/16/19371/32027.png
      - assets/offlineMap/16/19372/32024.png
      - assets/offlineMap/16/19372/32025.png
      - assets/offlineMap/16/19372/32026.png
      - assets/offlineMap/16/19372/32027.png
      - assets/offlineMap/16/19373/32024.png
      - assets/offlineMap/16/19373/32025.png
      - assets/offlineMap/16/19373/32026.png
      - assets/offlineMap/16/19373/32027.png
      - assets/offlineMap/16/19374/32024.png
      - assets/offlineMap/16/19374/32025.png
      - assets/offlineMap/16/19374/32026.png
      - assets/offlineMap/16/19374/32027.png
      - assets/offlineMap/17/38740/64049.png
      - assets/offlineMap/17/38740/64050.png
      - assets/offlineMap/17/38740/64051.png
      - assets/offlineMap/17/38740/64052.png
      - assets/offlineMap/17/38740/64053.png
      - assets/offlineMap/17/38740/64054.png
      - assets/offlineMap/17/38741/64049.png
      - assets/offlineMap/17/38741/64050.png
      - assets/offlineMap/17/38741/64051.png
      - assets/offlineMap/17/38741/64052.png
      - assets/offlineMap/17/38741/64053.png
      - assets/offlineMap/17/38741/64054.png
      - assets/offlineMap/17/38742/64049.png
      - assets/offlineMap/17/38742/64050.png
      - assets/offlineMap/17/38742/64051.png
      - assets/offlineMap/17/38742/64052.png
      - assets/offlineMap/17/38742/64053.png
      - assets/offlineMap/17/38742/64054.png
      - assets/offlineMap/17/38743/64049.png
      - assets/offlineMap/17/38743/64050.png
      - assets/offlineMap/17/38743/64051.png
      - assets/offlineMap/17/38743/64052.png
      - assets/offlineMap/17/38743/64053.png
      - assets/offlineMap/17/38743/64054.png
      - assets/offlineMap/17/38744/64049.png
      - assets/offlineMap/17/38744/64050.png
      - assets/offlineMap/17/38744/64051.png
      - assets/offlineMap/17/38744/64052.png
      - assets/offlineMap/17/38744/64053.png
      - assets/offlineMap/17/38744/64054.png
      - assets/offlineMap/17/38745/64049.png
      - assets/offlineMap/17/38745/64050.png
      - assets/offlineMap/17/38745/64051.png
      - assets/offlineMap/17/38745/64052.png
      - assets/offlineMap/17/38745/64053.png
      - assets/offlineMap/17/38745/64054.png
      - assets/offlineMap/17/38746/64049.png
      - assets/offlineMap/17/38746/64050.png
      - assets/offlineMap/17/38746/64051.png
      - assets/offlineMap/17/38746/64052.png
      - assets/offlineMap/17/38746/64053.png
      - assets/offlineMap/17/38746/64054.png
      - assets/offlineMap/17/38747/64049.png
      - assets/offlineMap/17/38747/64050.png
      - assets/offlineMap/17/38747/64051.png
      - assets/offlineMap/17/38747/64052.png
      - assets/offlineMap/17/38747/64053.png
      - assets/offlineMap/17/38747/64054.png
      - assets/offlineMap/17/38748/64049.png
      - assets/offlineMap/17/38748/64050.png
      - assets/offlineMap/17/38748/64051.png
      - assets/offlineMap/17/38748/64052.png
      - assets/offlineMap/17/38748/64053.png
      - assets/offlineMap/17/38748/64054.png
      - assets/offlineMap/18/77481/128098.png
      - assets/offlineMap/18/77481/128099.png
      - assets/offlineMap/18/77481/128100.png
      - assets/offlineMap/18/77481/128101.png
      - assets/offlineMap/18/77481/128102.png
      - assets/offlineMap/18/77481/128103.png
      - assets/offlineMap/18/77481/128104.png
      - assets/offlineMap/18/77481/128105.png
      - assets/offlineMap/18/77481/128106.png
      - assets/offlineMap/18/77481/128107.png
      - assets/offlineMap/18/77481/128108.png
      - assets/offlineMap/18/77482/128098.png
      - assets/offlineMap/18/77482/128099.png
      - assets/offlineMap/18/77482/128100.png
      - assets/offlineMap/18/77482/128101.png
      - assets/offlineMap/18/77482/128102.png
      - assets/offlineMap/18/77482/128103.png
      - assets/offlineMap/18/77482/128104.png
      - assets/offlineMap/18/77482/128105.png
      - assets/offlineMap/18/77482/128106.png
      - assets/offlineMap/18/77482/128107.png
      - assets/offlineMap/18/77482/128108.png
      - assets/offlineMap/18/77483/128098.png
      - assets/offlineMap/18/77483/128099.png
      - assets/offlineMap/18/77483/128100.png
      - assets/offlineMap/18/77483/128101.png
      - assets/offlineMap/18/77483/128102.png
      - assets/offlineMap/18/77483/128103.png
      - assets/offlineMap/18/77483/128104.png
      - assets/offlineMap/18/77483/128105.png
      - assets/offlineMap/18/77483/128106.png
      - assets/offlineMap/18/77483/128107.png
      - assets/offlineMap/18/77483/128108.png
      - assets/offlineMap/18/77484/128098.png
      - assets/offlineMap/18/77484/128099.png
      - assets/offlineMap/18/77484/128100.png
      - assets/offlineMap/18/77484/128101.png
      - assets/offlineMap/18/77484/128102.png
      - assets/offlineMap/18/77484/128103.png
      - assets/offlineMap/18/77484/128104.png
      - assets/offlineMap/18/77484/128105.png
      - assets/offlineMap/18/77484/128106.png
      - assets/offlineMap/18/77484/128107.png
      - assets/offlineMap/18/77484/128108.png
      - assets/offlineMap/18/77485/128098.png
      - assets/offlineMap/18/77485/128099.png
      - assets/offlineMap/18/77485/128100.png
      - assets/offlineMap/18/77485/128101.png
      - assets/offlineMap/18/77485/128102.png
      - assets/offlineMap/18/77485/128103.png
      - assets/offlineMap/18/77485/128104.png
      - assets/offlineMap/18/77485/128105.png
      - assets/offlineMap/18/77485/128106.png
      - assets/offlineMap/18/77485/128107.png
      - assets/offlineMap/18/77485/128108.png
      - assets/offlineMap/18/77486/128098.png
      - assets/offlineMap/18/77486/128099.png
      - assets/offlineMap/18/77486/128100.png
      - assets/offlineMap/18/77486/128101.png
      - assets/offlineMap/18/77486/128102.png
      - assets/offlineMap/18/77486/128103.png
      - assets/offlineMap/18/77486/128104.png
      - assets/offlineMap/18/77486/128105.png
      - assets/offlineMap/18/77486/128106.png
      - assets/offlineMap/18/77486/128107.png
      - assets/offlineMap/18/77486/128108.png
      - assets/offlineMap/18/77487/128098.png
      - assets/offlineMap/18/77487/128099.png
      - assets/offlineMap/18/77487/128100.png
      - assets/offlineMap/18/77487/128101.png
      - assets/offlineMap/18/77487/128102.png
      - assets/offlineMap/18/77487/128103.png
      - assets/offlineMap/18/77487/128104.png
      - assets/offlineMap/18/77487/128105.png
      - assets/offlineMap/18/77487/128106.png
      - assets/offlineMap/18/77487/128107.png
      - assets/offlineMap/18/77487/128108.png
      - assets/offlineMap/18/77488/128098.png
      - assets/offlineMap/18/77488/128099.png
      - assets/offlineMap/18/77488/128100.png
      - assets/offlineMap/18/77488/128101.png
      - assets/offlineMap/18/77488/128102.png
      - assets/offlineMap/18/77488/128103.png
      - assets/offlineMap/18/77488/128104.png
      - assets/offlineMap/18/77488/128105.png
      - assets/offlineMap/18/77488/128106.png
      - assets/offlineMap/18/77488/128107.png
      - assets/offlineMap/18/77488/128108.png
      - assets/offlineMap/18/77489/128098.png
      - assets/offlineMap/18/77489/128099.png
      - assets/offlineMap/18/77489/128100.png
      - assets/offlineMap/18/77489/128101.png
      - assets/offlineMap/18/77489/128102.png
      - assets/offlineMap/18/77489/128103.png
      - assets/offlineMap/18/77489/128104.png
      - assets/offlineMap/18/77489/128105.png
      - assets/offlineMap/18/77489/128106.png
      - assets/offlineMap/18/77489/128107.png
      - assets/offlineMap/18/77489/128108.png
      - assets/offlineMap/18/77490/128098.png
      - assets/offlineMap/18/77490/128099.png
      - assets/offlineMap/18/77490/128100.png
      - assets/offlineMap/18/77490/128101.png
      - assets/offlineMap/18/77490/128102.png
      - assets/offlineMap/18/77490/128103.png
      - assets/offlineMap/18/77490/128104.png
      - assets/offlineMap/18/77490/128105.png
      - assets/offlineMap/18/77490/128106.png
      - assets/offlineMap/18/77490/128107.png
      - assets/offlineMap/18/77490/128108.png
      - assets/offlineMap/18/77491/128098.png
      - assets/offlineMap/18/77491/128099.png
      - assets/offlineMap/18/77491/128100.png
      - assets/offlineMap/18/77491/128101.png
      - assets/offlineMap/18/77491/128102.png
      - assets/offlineMap/18/77491/128103.png
      - assets/offlineMap/18/77491/128104.png
      - assets/offlineMap/18/77491/128105.png
      - assets/offlineMap/18/77491/128106.png
      - assets/offlineMap/18/77491/128107.png
      - assets/offlineMap/18/77491/128108.png
      - assets/offlineMap/18/77492/128098.png
      - assets/offlineMap/18/77492/128099.png
      - assets/offlineMap/18/77492/128100.png
      - assets/offlineMap/18/77492/128101.png
      - assets/offlineMap/18/77492/128102.png
      - assets/offlineMap/18/77492/128103.png
      - assets/offlineMap/18/77492/128104.png
      - assets/offlineMap/18/77492/128105.png
      - assets/offlineMap/18/77492/128106.png
      - assets/offlineMap/18/77492/128107.png
      - assets/offlineMap/18/77492/128108.png
      - assets/offlineMap/18/77493/128098.png
      - assets/offlineMap/18/77493/128099.png
      - assets/offlineMap/18/77493/128100.png
      - assets/offlineMap/18/77493/128101.png
      - assets/offlineMap/18/77493/128102.png
      - assets/offlineMap/18/77493/128103.png
      - assets/offlineMap/18/77493/128104.png
      - assets/offlineMap/18/77493/128105.png
      - assets/offlineMap/18/77493/128106.png
      - assets/offlineMap/18/77493/128107.png
      - assets/offlineMap/18/77493/128108.png
      - assets/offlineMap/18/77494/128098.png
      - assets/offlineMap/18/77494/128099.png
      - assets/offlineMap/18/77494/128100.png
      - assets/offlineMap/18/77494/128101.png
      - assets/offlineMap/18/77494/128102.png
      - assets/offlineMap/18/77494/128103.png
      - assets/offlineMap/18/77494/128104.png
      - assets/offlineMap/18/77494/128105.png
      - assets/offlineMap/18/77494/128106.png
      - assets/offlineMap/18/77494/128107.png
      - assets/offlineMap/18/77494/128108.png
      - assets/offlineMap/18/77495/128098.png
      - assets/offlineMap/18/77495/128099.png
      - assets/offlineMap/18/77495/128100.png
      - assets/offlineMap/18/77495/128101.png
      - assets/offlineMap/18/77495/128102.png
      - assets/offlineMap/18/77495/128103.png
      - assets/offlineMap/18/77495/128104.png
      - assets/offlineMap/18/77495/128105.png
      - assets/offlineMap/18/77495/128106.png
      - assets/offlineMap/18/77495/128107.png
      - assets/offlineMap/18/77495/128108.png
      - assets/offlineMap/18/77496/128098.png
      - assets/offlineMap/18/77496/128099.png
      - assets/offlineMap/18/77496/128100.png
      - assets/offlineMap/18/77496/128101.png
      - assets/offlineMap/18/77496/128102.png
      - assets/offlineMap/18/77496/128103.png
      - assets/offlineMap/18/77496/128104.png
      - assets/offlineMap/18/77496/128105.png
      - assets/offlineMap/18/77496/128106.png
      - assets/offlineMap/18/77496/128107.png
      - assets/offlineMap/18/77496/128108.png
      - assets/offlineMap/18/77497/128098.png
      - assets/offlineMap/18/77497/128099.png
      - assets/offlineMap/18/77497/128100.png
      - assets/offlineMap/18/77497/128101.png
      - assets/offlineMap/18/77497/128102.png
      - assets/offlineMap/18/77497/128103.png
      - assets/offlineMap/18/77497/128104.png
      - assets/offlineMap/18/77497/128105.png
      - assets/offlineMap/18/77497/128106.png
      - assets/offlineMap/18/77497/128107.png
      - assets/offlineMap/18/77497/128108.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Archivo
       fonts:
         - asset: assets/fonts/Archivo-VariableFont_wdth,wght.ttf
         - asset: assets/fonts/Archivo-Italic-VariableFont_wdth,wght.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
